// Generated by scripts/generate-contracts.py. Do not edit.
// Upstream: a566d20d226a8e2ef0747639dc8a3fc1c43f9dba
// Schema SHA-256: cdfa614bba98b6eb4f13e0d929396238c89cca2c3b900fd44d9efddcc9da2a48
import Foundation

public enum GatewayContract {
    public static let upstreamCommit = "a566d20d226a8e2ef0747639dc8a3fc1c43f9dba"
    public static let schemaSHA256 = "cdfa614bba98b6eb4f13e0d929396238c89cca2c3b900fd44d9efddcc9da2a48"
}

public enum GatewayMethod: String, Sendable, CaseIterable, Codable {
    case `agentsList` = "agents.list"
    case `approvalPending` = "approval.pending"
    case `approvalReceived` = "approval.received"
    case `approvalRespond` = "approval.respond"
    case `billingAutoReload` = "billing.auto_reload"
    case `billingCharge` = "billing.charge"
    case `billingChargeStatus` = "billing.charge_status"
    case `billingState` = "billing.state"
    case `billingStepUp` = "billing.step_up"
    case `botRelayDeliver` = "bot_relay.deliver"
    case `botRelayOutboxDrain` = "bot_relay.outbox.drain"
    case `botRelayReply` = "bot_relay.reply"
    case `botRelayRosterSync` = "bot_relay.roster.sync"
    case `browserControllerDetach` = "browser.controller.detach"
    case `browserControllerHeartbeat` = "browser.controller.heartbeat"
    case `browserControllerRegister` = "browser.controller.register"
    case `browserControllerResult` = "browser.controller.result"
    case `browserManage` = "browser.manage"
    case `clarifyLock` = "clarify.lock"
    case `cliExec` = "cli.exec"
    case `clientCapabilities` = "client.capabilities"
    case `clipboardPaste` = "clipboard.paste"
    case `commandDispatch` = "command.dispatch"
    case `commandResolve` = "command.resolve"
    case `commandsCatalog` = "commands.catalog"
    case `completePath` = "complete.path"
    case `completeSlash` = "complete.slash"
    case `configGet` = "config.get"
    case `configSet` = "config.set"
    case `configShow` = "config.show"
    case `connectionRespond` = "connection.respond"
    case `connectorsConnect` = "connectors.connect"
    case `connectorsList` = "connectors.list"
    case `connectorsOperationStatus` = "connectors.operation.status"
    case `cronManage` = "cron.manage"
    case `delegationPause` = "delegation.pause"
    case `delegationStatus` = "delegation.status"
    case `diagnosticsShareNous` = "diagnostics.share_nous"
    case `fileAttach` = "file.attach"
    case `freeTierAckNotice` = "free_tier.ack_notice"
    case `freeTierProvision` = "free_tier.provision"
    case `freeTierStatus` = "free_tier.status"
    case `gatewayCapabilities` = "gateway.capabilities"
    case `groupsApprove` = "groups.approve"
    case `groupsCapabilities` = "groups.capabilities"
    case `groupsCreate` = "groups.create"
    case `groupsDemote` = "groups.demote"
    case `groupsDisband` = "groups.disband"
    case `groupsList` = "groups.list"
    case `groupsLog` = "groups.log"
    case `groupsPeerInvite` = "groups.peer.invite"
    case `groupsPeerRegister` = "groups.peer.register"
    case `groupsPeerRevoke` = "groups.peer.revoke"
    case `groupsPromote` = "groups.promote"
    case `groupsRename` = "groups.rename"
    case `groupsReplicaState` = "groups.replica_state"
    case `groupsReplicate` = "groups.replicate"
    case `groupsRetry` = "groups.retry"
    case `groupsSend` = "groups.send"
    case `groupsState` = "groups.state"
    case `groupsStop` = "groups.stop"
    case `handoffFail` = "handoff.fail"
    case `handoffRequest` = "handoff.request"
    case `handoffState` = "handoff.state"
    case `imageAttach` = "image.attach"
    case `imageAttachBytes` = "image.attach_bytes"
    case `imageDetach` = "image.detach"
    case `imageGenerate` = "image.generate"
    case `inputDetectDrop` = "input.detect_drop"
    case `insightsGet` = "insights.get"
    case `learningDelete` = "learning.delete"
    case `learningDetail` = "learning.detail"
    case `learningEdit` = "learning.edit"
    case `learningFrames` = "learning.frames"
    case `llmOneshot` = "llm.oneshot"
    case `mcpCatalog` = "mcp.catalog"
    case `mcpServersAdd` = "mcp.servers.add"
    case `mcpServersList` = "mcp.servers.list"
    case `mcpServersOauthCallback` = "mcp.servers.oauth.callback"
    case `mcpServersOauthCancel` = "mcp.servers.oauth.cancel"
    case `mcpServersOauthPoll` = "mcp.servers.oauth.poll"
    case `mcpServersOauthStart` = "mcp.servers.oauth.start"
    case `mcpServersRemove` = "mcp.servers.remove"
    case `mcpServersSetApiKey` = "mcp.servers.set_api_key"
    case `mcpServersStatus` = "mcp.servers.status"
    case `mcpServersTest` = "mcp.servers.test"
    case `messageReact` = "message.react"
    case `modelDisconnect` = "model.disconnect"
    case `modelOptions` = "model.options"
    case `modelSaveKey` = "model.save_key"
    case `pasteCollapse` = "paste.collapse"
    case `pdfAttach` = "pdf.attach"
    case `petCancel` = "pet.cancel"
    case `petCells` = "pet.cells"
    case `petDisable` = "pet.disable"
    case `petExport` = "pet.export"
    case `petGallery` = "pet.gallery"
    case `petGenerate` = "pet.generate"
    case `petGenerateStatus` = "pet.generate.status"
    case `petHatch` = "pet.hatch"
    case `petInfo` = "pet.info"
    case `petInfoMeta` = "pet.info.meta"
    case `petRemove` = "pet.remove"
    case `petRename` = "pet.rename"
    case `petScale` = "pet.scale"
    case `petSelect` = "pet.select"
    case `petThumb` = "pet.thumb"
    case `ping` = "ping"
    case `pluginsList` = "plugins.list"
    case `pluginsManage` = "plugins.manage"
    case `previewRestart` = "preview.restart"
    case `processKill` = "process.kill"
    case `processList` = "process.list"
    case `processStop` = "process.stop"
    case `profilesConfigure` = "profiles.configure"
    case `profilesCreate` = "profiles.create"
    case `profilesDescribe` = "profiles.describe"
    case `profilesGetAsset` = "profiles.get_asset"
    case `profilesList` = "profiles.list"
    case `profilesRememberOnboarding` = "profiles.remember_onboarding"
    case `profilesSetAsset` = "profiles.set_asset"
    case `projectFacts` = "project.facts"
    case `projectsAddFolder` = "projects.add_folder"
    case `projectsArchive` = "projects.archive"
    case `projectsCreate` = "projects.create"
    case `projectsDelete` = "projects.delete"
    case `projectsDiscoverRepos` = "projects.discover_repos"
    case `projectsForCwd` = "projects.for_cwd"
    case `projectsGet` = "projects.get"
    case `projectsList` = "projects.list"
    case `projectsProjectSessions` = "projects.project_sessions"
    case `projectsRecordRepos` = "projects.record_repos"
    case `projectsRemoveFolder` = "projects.remove_folder"
    case `projectsSetActive` = "projects.set_active"
    case `projectsSetPrimary` = "projects.set_primary"
    case `projectsTree` = "projects.tree"
    case `projectsUpdate` = "projects.update"
    case `promptBackground` = "prompt.background"
    case `promptBtw` = "prompt.btw"
    case `promptSubmit` = "prompt.submit"
    case `reloadEnv` = "reload.env"
    case `reloadMcp` = "reload.mcp"
    case `requestAnswer` = "request.answer"
    case `rollbackDiff` = "rollback.diff"
    case `rollbackList` = "rollback.list"
    case `rollbackRestore` = "rollback.restore"
    case `sessionActivate` = "session.activate"
    case `sessionActiveList` = "session.active_list"
    case `sessionBranch` = "session.branch"
    case `sessionClose` = "session.close"
    case `sessionCompress` = "session.compress"
    case `sessionContextBreakdown` = "session.context_breakdown"
    case `sessionControl` = "session.control"
    case `sessionControlRead` = "session.control.read"
    case `sessionCreate` = "session.create"
    case `sessionCwdSet` = "session.cwd.set"
    case `sessionDelete` = "session.delete"
    case `sessionEventsSince` = "session.events.since"
    case `sessionEventsStats` = "session.events.stats"
    case `sessionForeignImport` = "session.foreign.import"
    case `sessionForeignList` = "session.foreign.list"
    case `sessionForeignPreview` = "session.foreign.preview"
    case `sessionHistory` = "session.history"
    case `sessionInterrupt` = "session.interrupt"
    case `sessionList` = "session.list"
    case `sessionMostRecent` = "session.most_recent"
    case `sessionRedirect` = "session.redirect"
    case `sessionResume` = "session.resume"
    case `sessionSave` = "session.save"
    case `sessionSetHidden` = "session.set_hidden"
    case `sessionStatus` = "session.status"
    case `sessionSteer` = "session.steer"
    case `sessionTitle` = "session.title"
    case `sessionUndo` = "session.undo"
    case `sessionUsage` = "session.usage"
    case `sessionWorkspaceMove` = "session.workspace.move"
    case `setupRuntimeCheck` = "setup.runtime_check"
    case `setupStatus` = "setup.status"
    case `shellExec` = "shell.exec"
    case `skillsManage` = "skills.manage"
    case `skillsReload` = "skills.reload"
    case `slashExec` = "slash.exec"
    case `spawnTreeList` = "spawn_tree.list"
    case `spawnTreeLoad` = "spawn_tree.load"
    case `spawnTreeSave` = "spawn_tree.save"
    case `subagentInterrupt` = "subagent.interrupt"
    case `subagentList` = "subagent.list"
    case `subagentSteer` = "subagent.steer"
    case `subagentTail` = "subagent.tail"
    case `subscriptionChange` = "subscription.change"
    case `subscriptionPreview` = "subscription.preview"
    case `subscriptionResume` = "subscription.resume"
    case `subscriptionState` = "subscription.state"
    case `subscriptionUpgrade` = "subscription.upgrade"
    case `systemBattery` = "system.battery"
    case `terminalResize` = "terminal.resize"
    case `toolsConfigure` = "tools.configure"
    case `toolsList` = "tools.list"
    case `toolsShow` = "tools.show"
    case `toolsetsList` = "toolsets.list"
    case `usageBars` = "usage.bars"
    case `vaultAdd` = "vault.add"
    case `vaultList` = "vault.list"
    case `vaultLock` = "vault.lock"
    case `vaultRemove` = "vault.remove"
    case `vaultSourceSet` = "vault.source.set"
    case `vaultSources` = "vault.sources"
    case `vaultUnlock` = "vault.unlock"
    case `verificationStatus` = "verification.status"
    case `voiceRecord` = "voice.record"
    case `voiceToggle` = "voice.toggle"
    case `voiceTTS` = "voice.tts"
    case `wakeFeed` = "wake.feed"
    case `wakePause` = "wake.pause"
    case `wakeResume` = "wake.resume"
    case `wakeStart` = "wake.start"
    case `wakeStatus` = "wake.status"
    case `wakeStop` = "wake.stop"

    public var payloadSchema: String {
        switch self {
        case .`agentsList`: "AgentsListParams"
        case .`approvalPending`: "ApprovalPendingParams"
        case .`approvalReceived`: "ApprovalReceivedParams"
        case .`approvalRespond`: "ApprovalRespondParams"
        case .`billingAutoReload`: "BillingAutoReloadParams"
        case .`billingCharge`: "BillingChargeParams"
        case .`billingChargeStatus`: "BillingChargeStatusParams"
        case .`billingState`: "ProfileParams"
        case .`billingStepUp`: "BillingStepUpParams"
        case .`botRelayDeliver`: "BotRelayDeliverParams"
        case .`botRelayOutboxDrain`: "BotRelayOutboxDrainParams"
        case .`botRelayReply`: "BotRelayReplyParams"
        case .`botRelayRosterSync`: "BotRelayRosterSyncParams"
        case .`browserControllerDetach`: "BrowserControllerParams"
        case .`browserControllerHeartbeat`: "BrowserControllerParams"
        case .`browserControllerRegister`: "BrowserControllerRegisterParams"
        case .`browserControllerResult`: "BrowserControllerResultParams"
        case .`browserManage`: "BrowserManageParams"
        case .`clarifyLock`: "ClarifyLockParams"
        case .`cliExec`: "CliExecParams"
        case .`clientCapabilities`: "ClientCapabilitiesParams"
        case .`clipboardPaste`: "ClipboardPasteParams"
        case .`commandDispatch`: "CommandDispatchParams"
        case .`commandResolve`: "CommandResolveParams"
        case .`commandsCatalog`: "CommandsCatalogParams"
        case .`completePath`: "CompletePathParams"
        case .`completeSlash`: "CompleteSlashParams"
        case .`configGet`: "ConfigGetParams"
        case .`configSet`: "ConfigSetParams"
        case .`configShow`: "ConfigShowParams"
        case .`connectionRespond`: "ConnectionRespondParams"
        case .`connectorsConnect`: "ConnectorsConnectParams"
        case .`connectorsList`: "ConnectorsListParams"
        case .`connectorsOperationStatus`: "ConnectionOperationParams"
        case .`cronManage`: "CronManageParams"
        case .`delegationPause`: "DelegationPauseParams"
        case .`delegationStatus`: "ProfileParams"
        case .`diagnosticsShareNous`: "DiagnosticsShareNousParams"
        case .`fileAttach`: "FileAttachParams"
        case .`freeTierAckNotice`: "ProfileParams"
        case .`freeTierProvision`: "ProfileParams"
        case .`freeTierStatus`: "ProfileParams"
        case .`gatewayCapabilities`: "PingParams"
        case .`groupsApprove`: "GroupsApproveParams"
        case .`groupsCapabilities`: "GroupsCapabilitiesParams"
        case .`groupsCreate`: "GroupsCreateParams"
        case .`groupsDemote`: "GroupsDemoteParams"
        case .`groupsDisband`: "GroupsDisbandParams"
        case .`groupsList`: "GroupsListParams"
        case .`groupsLog`: "GroupsLogParams"
        case .`groupsPeerInvite`: "GroupsPeerInviteParams"
        case .`groupsPeerRegister`: "GroupsPeerRegisterParams"
        case .`groupsPeerRevoke`: "GroupsPeerRevokeParams"
        case .`groupsPromote`: "GroupsPromoteParams"
        case .`groupsRename`: "GroupsRenameParams"
        case .`groupsReplicaState`: "GroupsReplicaStateParams"
        case .`groupsReplicate`: "GroupsReplicateParams"
        case .`groupsRetry`: "GroupsRetryParams"
        case .`groupsSend`: "GroupsSendParams"
        case .`groupsState`: "GroupsStateParams"
        case .`groupsStop`: "GroupsStopParams"
        case .`handoffFail`: "HandoffFailParams"
        case .`handoffRequest`: "HandoffRequestParams"
        case .`handoffState`: "SessionParams"
        case .`imageAttach`: "ImageAttachParams"
        case .`imageAttachBytes`: "ImageAttachBytesParams"
        case .`imageDetach`: "ImageDetachParams"
        case .`imageGenerate`: "ImageGenerateParams"
        case .`inputDetectDrop`: "InputDetectDropParams"
        case .`insightsGet`: "InsightsGetParams"
        case .`learningDelete`: "LearningNodeParams"
        case .`learningDetail`: "LearningNodeParams"
        case .`learningEdit`: "LearningEditParams"
        case .`learningFrames`: "LearningFramesParams"
        case .`llmOneshot`: "LlmOneshotParams"
        case .`mcpCatalog`: "ProfileParams"
        case .`mcpServersAdd`: "McpServersAddParams"
        case .`mcpServersList`: "ProfileParams"
        case .`mcpServersOauthCallback`: "McpOauthCallbackParams"
        case .`mcpServersOauthCancel`: "McpOauthFlowParams"
        case .`mcpServersOauthPoll`: "McpOauthFlowParams"
        case .`mcpServersOauthStart`: "McpOauthStartParams"
        case .`mcpServersRemove`: "McpServerNameParams"
        case .`mcpServersSetApiKey`: "McpServersSetApiKeyParams"
        case .`mcpServersStatus`: "ProfileParams"
        case .`mcpServersTest`: "McpServerNameParams"
        case .`messageReact`: "MessageReactParams"
        case .`modelDisconnect`: "ModelDisconnectParams"
        case .`modelOptions`: "ModelOptionsParams"
        case .`modelSaveKey`: "ModelSaveKeyParams"
        case .`pasteCollapse`: "PasteCollapseParams"
        case .`pdfAttach`: "PdfAttachParams"
        case .`petCancel`: "PetCancelParams"
        case .`petCells`: "PetCellsParams"
        case .`petDisable`: "ProfileParams"
        case .`petExport`: "PetSlugParams"
        case .`petGallery`: "PetGalleryParams"
        case .`petGenerate`: "PetGenerateParams"
        case .`petGenerateStatus`: "ProfileParams"
        case .`petHatch`: "PetHatchParams"
        case .`petInfo`: "PetInfoParams"
        case .`petInfoMeta`: "ProfileParams"
        case .`petRemove`: "PetSlugParams"
        case .`petRename`: "PetRenameParams"
        case .`petScale`: "PetScaleParams"
        case .`petSelect`: "PetSlugParams"
        case .`petThumb`: "PetThumbParams"
        case .`ping`: "PingParams"
        case .`pluginsList`: "PluginsListParams"
        case .`pluginsManage`: "PluginsManageParams"
        case .`previewRestart`: "PreviewRestartParams"
        case .`processKill`: "ProcessKillParams"
        case .`processList`: "ProcessListParams"
        case .`processStop`: "ProcessStopParams"
        case .`profilesConfigure`: "ProfilesConfigureParams"
        case .`profilesCreate`: "ProfilesCreateParams"
        case .`profilesDescribe`: "ProfileNameParams"
        case .`profilesGetAsset`: "ProfilesGetAssetParams"
        case .`profilesList`: "ProfilesListParams"
        case .`profilesRememberOnboarding`: "ProfilesRememberOnboardingParams"
        case .`profilesSetAsset`: "ProfilesSetAssetParams"
        case .`projectFacts`: "ProjectFactsParams"
        case .`projectsAddFolder`: "ProjectsAddFolderParams"
        case .`projectsArchive`: "ProjectsArchiveParams"
        case .`projectsCreate`: "ProjectsCreateParams"
        case .`projectsDelete`: "ProjectIdParams"
        case .`projectsDiscoverRepos`: "ProjectsDiscoverReposParams"
        case .`projectsForCwd`: "ProjectsForCwdParams"
        case .`projectsGet`: "ProjectIdParams"
        case .`projectsList`: "ProfileParams"
        case .`projectsProjectSessions`: "ProjectsProjectSessionsParams"
        case .`projectsRecordRepos`: "ProjectsRecordReposParams"
        case .`projectsRemoveFolder`: "ProjectFolderParams"
        case .`projectsSetActive`: "ProjectsSetActiveParams"
        case .`projectsSetPrimary`: "ProjectFolderParams"
        case .`projectsTree`: "ProjectsTreeParams"
        case .`projectsUpdate`: "ProjectsUpdateParams"
        case .`promptBackground`: "SideAgentParams"
        case .`promptBtw`: "SideAgentParams"
        case .`promptSubmit`: "PromptSubmitParams"
        case .`reloadEnv`: "ReloadEnvParams"
        case .`reloadMcp`: "ReloadMcpParams"
        case .`requestAnswer`: "RequestAnswerParams"
        case .`rollbackDiff`: "RollbackDiffParams"
        case .`rollbackList`: "RollbackListParams"
        case .`rollbackRestore`: "RollbackRestoreParams"
        case .`sessionActivate`: "SessionActivateParams"
        case .`sessionActiveList`: "SessionActiveListParams"
        case .`sessionBranch`: "SessionBranchParams"
        case .`sessionClose`: "SessionCloseParams"
        case .`sessionCompress`: "SessionCompressParams"
        case .`sessionContextBreakdown`: "SessionContextBreakdownParams"
        case .`sessionControl`: "SessionControlParams"
        case .`sessionControlRead`: "SessionControlReadParams"
        case .`sessionCreate`: "SessionCreateParams"
        case .`sessionCwdSet`: "SessionCwdSetParams"
        case .`sessionDelete`: "SessionDeleteParams"
        case .`sessionEventsSince`: "SessionEventsSinceParams"
        case .`sessionEventsStats`: "SessionEventsStatsParams"
        case .`sessionForeignImport`: "SessionForeignIdParams"
        case .`sessionForeignList`: "SessionForeignListParams"
        case .`sessionForeignPreview`: "SessionForeignIdParams"
        case .`sessionHistory`: "SessionHistoryParams"
        case .`sessionInterrupt`: "SessionInterruptParams"
        case .`sessionList`: "SessionListParams"
        case .`sessionMostRecent`: "SessionMostRecentParams"
        case .`sessionRedirect`: "SessionCorrectionParams"
        case .`sessionResume`: "SessionResumeParams"
        case .`sessionSave`: "SessionSaveParams"
        case .`sessionSetHidden`: "SessionSetHiddenParams"
        case .`sessionStatus`: "SessionStatusParams"
        case .`sessionSteer`: "SessionCorrectionParams"
        case .`sessionTitle`: "SessionTitleParams"
        case .`sessionUndo`: "SessionUndoParams"
        case .`sessionUsage`: "SessionUsageParams"
        case .`sessionWorkspaceMove`: "SessionWorkspaceMoveParams"
        case .`setupRuntimeCheck`: "SetupRuntimeCheckParams"
        case .`setupStatus`: "ProfileParams"
        case .`shellExec`: "ShellExecParams"
        case .`skillsManage`: "SkillsManageParams"
        case .`skillsReload`: "SkillsReloadParams"
        case .`slashExec`: "SlashExecParams"
        case .`spawnTreeList`: "SpawnTreeListParams"
        case .`spawnTreeLoad`: "SpawnTreeLoadParams"
        case .`spawnTreeSave`: "SpawnTreeSaveParams"
        case .`subagentInterrupt`: "SubagentIdParams"
        case .`subagentList`: "SessionParams"
        case .`subagentSteer`: "SubagentSteerParams"
        case .`subagentTail`: "SubagentIdParams"
        case .`subscriptionChange`: "SubscriptionChangeParams"
        case .`subscriptionPreview`: "SubscriptionPreviewParams"
        case .`subscriptionResume`: "ProfileParams"
        case .`subscriptionState`: "ProfileParams"
        case .`subscriptionUpgrade`: "SubscriptionUpgradeParams"
        case .`systemBattery`: "SystemBatteryParams"
        case .`terminalResize`: "TerminalResizeParams"
        case .`toolsConfigure`: "ToolsConfigureParams"
        case .`toolsList`: "_SessionScoped"
        case .`toolsShow`: "_SessionScoped"
        case .`toolsetsList`: "_SessionScoped"
        case .`usageBars`: "ProfileParams"
        case .`vaultAdd`: "VaultAddParams"
        case .`vaultList`: "ProfileParams"
        case .`vaultLock`: "VaultLockParams"
        case .`vaultRemove`: "VaultRemoveParams"
        case .`vaultSourceSet`: "VaultSourceSetParams"
        case .`vaultSources`: "ProfileParams"
        case .`vaultUnlock`: "VaultUnlockParams"
        case .`verificationStatus`: "VerificationStatusParams"
        case .`voiceRecord`: "VoiceRecordParams"
        case .`voiceToggle`: "VoiceToggleParams"
        case .`voiceTTS`: "VoiceTtsParams"
        case .`wakeFeed`: "WakeFeedParams"
        case .`wakePause`: "WakeControlParams"
        case .`wakeResume`: "WakeControlParams"
        case .`wakeStart`: "WakeStartParams"
        case .`wakeStatus`: "WakeStatusParams"
        case .`wakeStop`: "WakeStopParams"
        }
    }

    public var resultSchema: String {
        switch self {
        case .`agentsList`: "AgentsListResult"
        case .`approvalPending`: "ApprovalPendingResult"
        case .`approvalReceived`: "ApprovalReceivedResult"
        case .`approvalRespond`: "ApprovalRespondResult"
        case .`billingAutoReload`: "BillingMutationResult"
        case .`billingCharge`: "BillingChargeResult"
        case .`billingChargeStatus`: "BillingChargeStatusResult"
        case .`billingState`: "BillingStateResult"
        case .`billingStepUp`: "BillingStepUpResult"
        case .`botRelayDeliver`: "BotRelayDeliverResult"
        case .`botRelayOutboxDrain`: "BotRelayOutboxDrainResult"
        case .`botRelayReply`: "OkResult"
        case .`botRelayRosterSync`: "BotRelayRosterSyncResult"
        case .`browserControllerDetach`: "BrowserControllerDetachResult"
        case .`browserControllerHeartbeat`: "OkResult"
        case .`browserControllerRegister`: "BrowserControllerRegisterResult"
        case .`browserControllerResult`: "BrowserControllerResultResult"
        case .`browserManage`: "BrowserManageResult"
        case .`clarifyLock`: "ClarifyLockResult"
        case .`cliExec`: "CliExecResult"
        case .`clientCapabilities`: "ClientCapabilitiesResult"
        case .`clipboardPaste`: "AttachedImageResult"
        case .`commandDispatch`: "CommandDispatchResult"
        case .`commandResolve`: "CommandResolveResult"
        case .`commandsCatalog`: "CommandsCatalogResult"
        case .`completePath`: "CompletionItemsResult"
        case .`completeSlash`: "CompleteSlashResult"
        case .`configGet`: "ConfigGetResult"
        case .`configSet`: "ConfigSetResult"
        case .`configShow`: "ConfigShowResult"
        case .`connectionRespond`: "ConnectionRespondResult"
        case .`connectorsConnect`: "ConnectorsConnectResult"
        case .`connectorsList`: "ConnectorsListResult"
        case .`connectorsOperationStatus`: "ConnectionOperationStatus"
        case .`cronManage`: "CronManageResult"
        case .`delegationPause`: "DelegationPauseResult"
        case .`delegationStatus`: "DelegationStatusResult"
        case .`diagnosticsShareNous`: "DiagnosticsShareNousResult"
        case .`fileAttach`: "FileAttachResult"
        case .`freeTierAckNotice`: "FreeTierAckNoticeResult"
        case .`freeTierProvision`: "FreeTierProvisionResult"
        case .`freeTierStatus`: "FreeTierStatusResult"
        case .`gatewayCapabilities`: "GatewayCapabilitiesResult"
        case .`groupsApprove`: "GroupsApproveResult"
        case .`groupsCapabilities`: "GroupsCapabilitiesResult"
        case .`groupsCreate`: "GroupsCreateResult"
        case .`groupsDemote`: "GroupsDemoteResult"
        case .`groupsDisband`: "GroupsDisbandResult"
        case .`groupsList`: "GroupsListResult"
        case .`groupsLog`: "GroupsLogResult"
        case .`groupsPeerInvite`: "GroupsPeerInviteResult"
        case .`groupsPeerRegister`: "GroupsPeerRegisterResult"
        case .`groupsPeerRevoke`: "GroupsPeerRevokeResult"
        case .`groupsPromote`: "GroupsPromoteResult"
        case .`groupsRename`: "GroupsRenameResult"
        case .`groupsReplicaState`: "GroupsReplicaStateResult"
        case .`groupsReplicate`: "GroupsReplicateResult"
        case .`groupsRetry`: "GroupsRetryResult"
        case .`groupsSend`: "GroupsSendResult"
        case .`groupsState`: "GroupsStateResult"
        case .`groupsStop`: "GroupsStopResult"
        case .`handoffFail`: "HandoffFailResult"
        case .`handoffRequest`: "HandoffRequestResult"
        case .`handoffState`: "HandoffStateResult"
        case .`imageAttach`: "AttachedImageResult"
        case .`imageAttachBytes`: "AttachedImageResult"
        case .`imageDetach`: "ImageDetachResult"
        case .`imageGenerate`: "ImageGenerateResult"
        case .`inputDetectDrop`: "InputDetectDropResult"
        case .`insightsGet`: "InsightsGetResult"
        case .`learningDelete`: "LearningMutationResult"
        case .`learningDetail`: "LearningDetailResult"
        case .`learningEdit`: "LearningMutationResult"
        case .`learningFrames`: "LearningFramesResult"
        case .`llmOneshot`: "LlmOneshotResult"
        case .`mcpCatalog`: "McpCatalogResult"
        case .`mcpServersAdd`: "McpServersAddResult"
        case .`mcpServersList`: "McpServersListResult"
        case .`mcpServersOauthCallback`: "McpOauthCallbackResult"
        case .`mcpServersOauthCancel`: "McpOauthCancelResult"
        case .`mcpServersOauthPoll`: "McpOauthPollResult"
        case .`mcpServersOauthStart`: "McpOauthStartResult"
        case .`mcpServersRemove`: "McpServersRemoveResult"
        case .`mcpServersSetApiKey`: "McpServersSetApiKeyResult"
        case .`mcpServersStatus`: "McpServersStatusResult"
        case .`mcpServersTest`: "McpServersTestResult"
        case .`messageReact`: "MessageReactResult"
        case .`modelDisconnect`: "ModelDisconnectResult"
        case .`modelOptions`: "ModelOptionsResult"
        case .`modelSaveKey`: "ModelSaveKeyResult"
        case .`pasteCollapse`: "PasteCollapseResult"
        case .`pdfAttach`: "PdfAttachResult"
        case .`petCancel`: "PetCancelResult"
        case .`petCells`: "PetCellsResult"
        case .`petDisable`: "OkResult"
        case .`petExport`: "PetExportResult"
        case .`petGallery`: "PetGalleryResult"
        case .`petGenerate`: "PetGenerateResult"
        case .`petGenerateStatus`: "PetGenerateStatusResult"
        case .`petHatch`: "PetHatchResult"
        case .`petInfo`: "PetInfoResult"
        case .`petInfoMeta`: "PetInfoMetaResult"
        case .`petRemove`: "PetSlugResult"
        case .`petRename`: "PetSlugResult"
        case .`petScale`: "PetScaleResult"
        case .`petSelect`: "PetSlugResult"
        case .`petThumb`: "PetThumbResult"
        case .`ping`: "PingResult"
        case .`pluginsList`: "PluginsListResult"
        case .`pluginsManage`: "PluginsManageResult"
        case .`previewRestart`: "TaskIdResult"
        case .`processKill`: "ProcessKillResult"
        case .`processList`: "ProcessListResult"
        case .`processStop`: "ProcessStopResult"
        case .`profilesConfigure`: "ProfilesConfigureResult"
        case .`profilesCreate`: "ProfilesCreateResult"
        case .`profilesDescribe`: "ProfilesDescribeResult"
        case .`profilesGetAsset`: "ProfilesGetAssetResult"
        case .`profilesList`: "ProfilesListResult"
        case .`profilesRememberOnboarding`: "ProfilesRememberOnboardingResult"
        case .`profilesSetAsset`: "ProfilesSetAssetResult"
        case .`projectFacts`: "ProjectFactsResult"
        case .`projectsAddFolder`: "ProjectResult"
        case .`projectsArchive`: "ProjectsPayload"
        case .`projectsCreate`: "OptionalProjectResult"
        case .`projectsDelete`: "ProjectsPayload"
        case .`projectsDiscoverRepos`: "ProjectsDiscoverReposResult"
        case .`projectsForCwd`: "ProjectsForCwdResult"
        case .`projectsGet`: "ProjectResult"
        case .`projectsList`: "ProjectsPayload"
        case .`projectsProjectSessions`: "ProjectsProjectSessionsResult"
        case .`projectsRecordRepos`: "ProjectsRecordReposResult"
        case .`projectsRemoveFolder`: "ProjectResult"
        case .`projectsSetActive`: "ActiveIdResult"
        case .`projectsSetPrimary`: "ProjectResult"
        case .`projectsTree`: "ProjectsTreeResult"
        case .`projectsUpdate`: "ProjectResult"
        case .`promptBackground`: "TaskIdResult"
        case .`promptBtw`: "TaskIdResult"
        case .`promptSubmit`: "PromptSubmitResult"
        case .`reloadEnv`: "ReloadEnvResult"
        case .`reloadMcp`: "ReloadMcpResult"
        case .`requestAnswer`: "RequestAnswerResult"
        case .`rollbackDiff`: "RollbackDiffResult"
        case .`rollbackList`: "RollbackListResult"
        case .`rollbackRestore`: "RollbackRestoreResult"
        case .`sessionActivate`: "SessionActivateResult"
        case .`sessionActiveList`: "SessionActiveListResult"
        case .`sessionBranch`: "SessionBranchResult"
        case .`sessionClose`: "SessionCloseResult"
        case .`sessionCompress`: "SessionCompressResult"
        case .`sessionContextBreakdown`: "SessionContextBreakdownResult"
        case .`sessionControl`: "SessionControlResult"
        case .`sessionControlRead`: "SessionControlReadResult"
        case .`sessionCreate`: "SessionCreateResult"
        case .`sessionCwdSet`: "SessionCwdSetResult"
        case .`sessionDelete`: "SessionDeleteResult"
        case .`sessionEventsSince`: "SessionEventsSinceResult"
        case .`sessionEventsStats`: "SessionEventsStatsResult"
        case .`sessionForeignImport`: "SessionForeignImportResult"
        case .`sessionForeignList`: "SessionForeignListResult"
        case .`sessionForeignPreview`: "SessionForeignPreviewResult"
        case .`sessionHistory`: "SessionHistoryResult"
        case .`sessionInterrupt`: "SessionInterruptResult"
        case .`sessionList`: "SessionListResult"
        case .`sessionMostRecent`: "SessionMostRecentResult"
        case .`sessionRedirect`: "SessionCorrectionResult"
        case .`sessionResume`: "SessionResumeResult"
        case .`sessionSave`: "SessionSaveResult"
        case .`sessionSetHidden`: "SessionSetHiddenResult"
        case .`sessionStatus`: "SessionStatusResult"
        case .`sessionSteer`: "SessionCorrectionResult"
        case .`sessionTitle`: "SessionTitleResult"
        case .`sessionUndo`: "SessionUndoResult"
        case .`sessionUsage`: "SessionUsageResult"
        case .`sessionWorkspaceMove`: "SessionWorkspaceMoveResult"
        case .`setupRuntimeCheck`: "SetupRuntimeCheckResult"
        case .`setupStatus`: "SetupStatusResult"
        case .`shellExec`: "ShellExecResult"
        case .`skillsManage`: "SkillsManageResult"
        case .`skillsReload`: "SkillsReloadResult"
        case .`slashExec`: "SlashExecResult"
        case .`spawnTreeList`: "SpawnTreeListResult"
        case .`spawnTreeLoad`: "SpawnTreeLoadResult"
        case .`spawnTreeSave`: "SpawnTreeSaveResult"
        case .`subagentInterrupt`: "SubagentInterruptResult"
        case .`subagentList`: "SubagentListResult"
        case .`subagentSteer`: "SubagentSteerResult"
        case .`subagentTail`: "SubagentTailResult"
        case .`subscriptionChange`: "BillingPendingChangeResult"
        case .`subscriptionPreview`: "SubscriptionPreviewResult"
        case .`subscriptionResume`: "BillingPendingChangeResult"
        case .`subscriptionState`: "SubscriptionStateResult"
        case .`subscriptionUpgrade`: "SubscriptionUpgradeResult"
        case .`systemBattery`: "SystemBatteryResult"
        case .`terminalResize`: "TerminalResizeResult"
        case .`toolsConfigure`: "ToolsConfigureResult"
        case .`toolsList`: "ToolsetsListResult"
        case .`toolsShow`: "ToolsShowResult"
        case .`toolsetsList`: "ToolsetsListResult"
        case .`usageBars`: "UsageModel"
        case .`vaultAdd`: "VaultAddResult"
        case .`vaultList`: "VaultListResult"
        case .`vaultLock`: "VaultLockResult"
        case .`vaultRemove`: "VaultRemoveResult"
        case .`vaultSourceSet`: "VaultSourceSetResult"
        case .`vaultSources`: "VaultSourcesResult"
        case .`vaultUnlock`: "VaultUnlockResult"
        case .`verificationStatus`: "VerificationStatusResult"
        case .`voiceRecord`: "VoiceRecordResult"
        case .`voiceToggle`: "VoiceToggleResult"
        case .`voiceTTS`: "VoiceTtsResult"
        case .`wakeFeed`: "WakeFeedResult"
        case .`wakePause`: "WakePauseResult"
        case .`wakeResume`: "WakeResumeResult"
        case .`wakeStart`: "WakeStartResult"
        case .`wakeStatus`: "WakeStatusResult"
        case .`wakeStop`: "WakeStopResult"
        }
    }
}

public enum GatewayServerRequestMethod: String, Sendable, CaseIterable, Codable {
    case `approval` = "approval"
    case `clarify` = "clarify"
    case `previewAct` = "preview.act"
    case `previewRead` = "preview.read"
    case `secret` = "secret"
    case `sudo` = "sudo"
    case `terminalRead` = "terminal.read"
    case `tour` = "tour"
    case `vaultCode` = "vault.code"
    case `vaultSaveLogin` = "vault.save_login"
    case `vaultUnlockPrompt` = "vault.unlock_prompt"
    case `windowRead` = "window.read"

    public var payloadSchema: String {
        switch self {
        case .`approval`: "ApprovalRequestParams"
        case .`clarify`: "ClarifyRequestParams"
        case .`previewAct`: "PreviewActRequestParams"
        case .`previewRead`: "ReadRangeRequestParams"
        case .`secret`: "SecretRequestParams"
        case .`sudo`: "SudoRequestParams"
        case .`terminalRead`: "ReadRangeRequestParams"
        case .`tour`: "TourRequestParams"
        case .`vaultCode`: "VaultCodeRequestParams"
        case .`vaultSaveLogin`: "VaultSaveLoginRequestParams"
        case .`vaultUnlockPrompt`: "VaultUnlockRequestParams"
        case .`windowRead`: "EmptyRequestParams"
        }
    }

    public var resultSchema: String {
        switch self {
        case .`approval`: "ApprovalResult"
        case .`clarify`: "ClarifyResult"
        case .`previewAct`: "ValueResult"
        case .`previewRead`: "ValueResult"
        case .`secret`: "ValueResult"
        case .`sudo`: "ValueResult"
        case .`terminalRead`: "ValueResult"
        case .`tour`: "ValueResult"
        case .`vaultCode`: "ValueResult"
        case .`vaultSaveLogin`: "ValueResult"
        case .`vaultUnlockPrompt`: "ValueResult"
        case .`windowRead`: "ValueResult"
        }
    }
}

public enum GatewayEventType: String, Sendable, CaseIterable, Codable {
    case `agentTerminalOutput` = "agent.terminal.output"
    case `backgroundComplete` = "background.complete"
    case `billingStepUpVerification` = "billing.step_up.verification"
    case `botRelayOutboxPending` = "bot_relay.outbox.pending"
    case `browserControllerCancel` = "browser.controller.cancel"
    case `browserControllerCommand` = "browser.controller.command"
    case `browserProgress` = "browser.progress"
    case `btwComplete` = "btw.complete"
    case `connectionRequest` = "connection.request"
    case `connectionUpdate` = "connection.update"
    case `cronChanged` = "cron.changed"
    case `error` = "error"
    case `gatewayReady` = "gateway.ready"
    case `layoutApply` = "layout.apply"
    case `messageComplete` = "message.complete"
    case `messageDelta` = "message.delta"
    case `messageInterim` = "message.interim"
    case `messageReaction` = "message.reaction"
    case `messageStart` = "message.start"
    case `moaAggregating` = "moa.aggregating"
    case `moaPhase` = "moa.phase"
    case `moaProgress` = "moa.progress"
    case `moaReference` = "moa.reference"
    case `notice` = "notice"
    case `notificationClear` = "notification.clear"
    case `notificationShow` = "notification.show"
    case `pairingChanged` = "pairing.changed"
    case `paneReveal` = "pane.reveal"
    case `petChanged` = "pet.changed"
    case `petGenerateProgress` = "pet.generate.progress"
    case `petHatchProgress` = "pet.hatch.progress"
    case `platformsChanged` = "platforms.changed"
    case `previewClose` = "preview.close"
    case `previewOpen` = "preview.open"
    case `previewRestartComplete` = "preview.restart.complete"
    case `previewRestartProgress` = "preview.restart.progress"
    case `reaction` = "reaction"
    case `reasoningAvailable` = "reasoning.available"
    case `reasoningDelta` = "reasoning.delta"
    case `requestCancel` = "request.cancel"
    case `reviewSummary` = "review.summary"
    case `sessionControlUpdate` = "session.control.update"
    case `sessionInfo` = "session.info"
    case `sessionReclaimed` = "session.reclaimed"
    case `sessionResumeProgress` = "session.resume_progress"
    case `sessionTitle` = "session.title"
    case `sessionUsage` = "session.usage"
    case `sessionsChanged` = "sessions.changed"
    case `setupReady` = "setup.ready"
    case `skinChanged` = "skin.changed"
    case `statusUpdate` = "status.update"
    case `subagentComplete` = "subagent.complete"
    case `subagentProgress` = "subagent.progress"
    case `subagentSpawnRequested` = "subagent.spawn_requested"
    case `subagentStart` = "subagent.start"
    case `subagentThinking` = "subagent.thinking"
    case `subagentTool` = "subagent.tool"
    case `terminalClose` = "terminal.close"
    case `thinkingDelta` = "thinking.delta"
    case `tipShow` = "tip.show"
    case `todoUpdated` = "todo.updated"
    case `toolComplete` = "tool.complete"
    case `toolGenerating` = "tool.generating"
    case `toolOutputRisk` = "tool.output_risk"
    case `toolStart` = "tool.start"
    case `voiceInterrupted` = "voice.interrupted"
    case `voiceStatus` = "voice.status"
    case `voiceTranscript` = "voice.transcript"
    case `wakeDetected` = "wake.detected"

    public var payloadSchema: String {
        switch self {
        case .`agentTerminalOutput`: "TerminalOutputPayload"
        case .`backgroundComplete`: "SideAgentCompletePayload"
        case .`billingStepUpVerification`: "BillingStepUpVerificationPayload"
        case .`botRelayOutboxPending`: "ChangeSignalPayload"
        case .`browserControllerCancel`: "BrowserControllerCancelPayload"
        case .`browserControllerCommand`: "BrowserControllerCommandPayload"
        case .`browserProgress`: "BrowserProgressPayload"
        case .`btwComplete`: "SideAgentCompletePayload"
        case .`connectionRequest`: "ConnectionRequestPayload"
        case .`connectionUpdate`: "ConnectionUpdatePayload"
        case .`cronChanged`: "ChangeSignalPayload"
        case .`error`: "ErrorPayload"
        case .`gatewayReady`: "GatewayReadyPayload"
        case .`layoutApply`: "LayoutApplyPayload"
        case .`messageComplete`: "MessageCompletePayload"
        case .`messageDelta`: "StreamDeltaPayload"
        case .`messageInterim`: "MessageInterimPayload"
        case .`messageReaction`: "MessageReactionPayload"
        case .`messageStart`: "EmptyObject"
        case .`moaAggregating`: "MoaAggregatingPayload"
        case .`moaPhase`: "MoaPhasePayload"
        case .`moaProgress`: "MoaProgressPayload"
        case .`moaReference`: "MoaReferencePayload"
        case .`notice`: "NoticePayload"
        case .`notificationClear`: "NotificationClearPayload"
        case .`notificationShow`: "NotificationShowPayload"
        case .`pairingChanged`: "ChangeSignalPayload"
        case .`paneReveal`: "PaneRevealPayload"
        case .`petChanged`: "PetChangedPayload"
        case .`petGenerateProgress`: "PetGenerateProgressPayload"
        case .`petHatchProgress`: "PetHatchProgressPayload"
        case .`platformsChanged`: "ChangeSignalPayload"
        case .`previewClose`: "PreviewClosePayload"
        case .`previewOpen`: "PreviewOpenPayload"
        case .`previewRestartComplete`: "SideAgentCompletePayload"
        case .`previewRestartProgress`: "PreviewRestartProgressPayload"
        case .`reaction`: "ReactionPayload"
        case .`reasoningAvailable`: "StreamDeltaPayload"
        case .`reasoningDelta`: "StreamDeltaPayload"
        case .`requestCancel`: "RequestCancelPayload"
        case .`reviewSummary`: "ReviewSummaryPayload"
        case .`sessionControlUpdate`: "SessionControlUpdatePayload"
        case .`sessionInfo`: "SessionLiveInfo"
        case .`sessionReclaimed`: "SessionReclaimedPayload"
        case .`sessionResumeProgress`: "SessionResumeProgressPayload"
        case .`sessionTitle`: "SessionTitlePayload"
        case .`sessionUsage`: "SessionUsagePayload"
        case .`sessionsChanged`: "ChangeSignalPayload"
        case .`setupReady`: "SetupReadyPayload"
        case .`skinChanged`: "SkinPayload"
        case .`statusUpdate`: "StatusUpdatePayload"
        case .`subagentComplete`: "SubagentEventPayload"
        case .`subagentProgress`: "SubagentEventPayload"
        case .`subagentSpawnRequested`: "SubagentEventPayload"
        case .`subagentStart`: "SubagentEventPayload"
        case .`subagentThinking`: "SubagentEventPayload"
        case .`subagentTool`: "SubagentEventPayload"
        case .`terminalClose`: "TerminalClosePayload"
        case .`thinkingDelta`: "StreamDeltaPayload"
        case .`tipShow`: "TipShowPayload"
        case .`todoUpdated`: "TodoUpdatedPayload"
        case .`toolComplete`: "ToolCompletePayload"
        case .`toolGenerating`: "ToolGeneratingPayload"
        case .`toolOutputRisk`: "ToolOutputRiskPayload"
        case .`toolStart`: "ToolStartPayload"
        case .`voiceInterrupted`: "EmptyObject"
        case .`voiceStatus`: "VoiceStatusPayload"
        case .`voiceTranscript`: "VoiceTranscriptPayload"
        case .`wakeDetected`: "WakeDetectedPayload"
        }
    }
}

/// Wire schema: `ClientCapabilitiesParams`. Complex referenced objects retain their full JSON structure.
public struct ClientCapabilitiesParams: Sendable, Codable, Equatable {
    public var `serverRequests`: Bool?

    public init(
        `serverRequests`: Bool? = nil
    ) {
        self.`serverRequests` = `serverRequests`
    }

    private enum CodingKeys: String, CodingKey {
        case `serverRequests` = "server_requests"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `serverRequests` = try container.decodeOmittable(Bool.self, forKey: .`serverRequests`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(`serverRequests`, forKey: .`serverRequests`)
    }
}

/// Wire schema: `ClientCapabilitiesResult`. Complex referenced objects retain their full JSON structure.
public struct ClientCapabilitiesResult: Sendable, Codable, Equatable {
    public var `serverRequests`: [String]

    public init(
        `serverRequests`: [String]
    ) {
        self.`serverRequests` = `serverRequests`
    }

    private enum CodingKeys: String, CodingKey {
        case `serverRequests` = "server_requests"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `serverRequests` = try container.decode([String].self, forKey: .`serverRequests`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`serverRequests`, forKey: .`serverRequests`)
    }
}

/// Wire schema: `SessionCreateParams`. Complex referenced objects retain their full JSON structure.
public struct SessionCreateParams: Sendable, Codable, Equatable {
    public var `profile`: JSONField<String>
    public var `cols`: JSONField<Int>
    public var `source`: JSONField<String>
    public var `cwd`: JSONField<String>
    public var `messages`: JSONField<[JSONValue]>
    public var `parentSessionID`: JSONField<String>
    public var `title`: JSONField<String>
    public var `model`: JSONField<String>
    public var `provider`: JSONField<String>
    public var `reasoningEffort`: JSONField<String>
    public var `fast`: JSONField<Bool>
    public var `closeOnDisconnect`: Bool?
    public var `hidden`: Bool?
    public var `roomPlumbing`: Bool?
    public var `followProfileConfig`: Bool?

    public init(
        `profile`: JSONField<String> = .absent,
        `cols`: JSONField<Int> = .absent,
        `source`: JSONField<String> = .absent,
        `cwd`: JSONField<String> = .absent,
        `messages`: JSONField<[JSONValue]> = .absent,
        `parentSessionID`: JSONField<String> = .absent,
        `title`: JSONField<String> = .absent,
        `model`: JSONField<String> = .absent,
        `provider`: JSONField<String> = .absent,
        `reasoningEffort`: JSONField<String> = .absent,
        `fast`: JSONField<Bool> = .absent,
        `closeOnDisconnect`: Bool? = nil,
        `hidden`: Bool? = nil,
        `roomPlumbing`: Bool? = nil,
        `followProfileConfig`: Bool? = nil
    ) {
        self.`profile` = `profile`
        self.`cols` = `cols`
        self.`source` = `source`
        self.`cwd` = `cwd`
        self.`messages` = `messages`
        self.`parentSessionID` = `parentSessionID`
        self.`title` = `title`
        self.`model` = `model`
        self.`provider` = `provider`
        self.`reasoningEffort` = `reasoningEffort`
        self.`fast` = `fast`
        self.`closeOnDisconnect` = `closeOnDisconnect`
        self.`hidden` = `hidden`
        self.`roomPlumbing` = `roomPlumbing`
        self.`followProfileConfig` = `followProfileConfig`
    }

    private enum CodingKeys: String, CodingKey {
        case `profile` = "profile"
        case `cols` = "cols"
        case `source` = "source"
        case `cwd` = "cwd"
        case `messages` = "messages"
        case `parentSessionID` = "parent_session_id"
        case `title` = "title"
        case `model` = "model"
        case `provider` = "provider"
        case `reasoningEffort` = "reasoning_effort"
        case `fast` = "fast"
        case `closeOnDisconnect` = "close_on_disconnect"
        case `hidden` = "hidden"
        case `roomPlumbing` = "room_plumbing"
        case `followProfileConfig` = "follow_profile_config"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `profile` = try container.decodeField(String.self, forKey: .`profile`)
        `cols` = try container.decodeField(Int.self, forKey: .`cols`)
        `source` = try container.decodeField(String.self, forKey: .`source`)
        `cwd` = try container.decodeField(String.self, forKey: .`cwd`)
        `messages` = try container.decodeField([JSONValue].self, forKey: .`messages`)
        `parentSessionID` = try container.decodeField(String.self, forKey: .`parentSessionID`)
        `title` = try container.decodeField(String.self, forKey: .`title`)
        `model` = try container.decodeField(String.self, forKey: .`model`)
        `provider` = try container.decodeField(String.self, forKey: .`provider`)
        `reasoningEffort` = try container.decodeField(String.self, forKey: .`reasoningEffort`)
        `fast` = try container.decodeField(Bool.self, forKey: .`fast`)
        `closeOnDisconnect` = try container.decodeOmittable(Bool.self, forKey: .`closeOnDisconnect`)
        `hidden` = try container.decodeOmittable(Bool.self, forKey: .`hidden`)
        `roomPlumbing` = try container.decodeOmittable(Bool.self, forKey: .`roomPlumbing`)
        `followProfileConfig` = try container.decodeOmittable(Bool.self, forKey: .`followProfileConfig`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeField(`profile`, forKey: .`profile`)
        try container.encodeField(`cols`, forKey: .`cols`)
        try container.encodeField(`source`, forKey: .`source`)
        try container.encodeField(`cwd`, forKey: .`cwd`)
        try container.encodeField(`messages`, forKey: .`messages`)
        try container.encodeField(`parentSessionID`, forKey: .`parentSessionID`)
        try container.encodeField(`title`, forKey: .`title`)
        try container.encodeField(`model`, forKey: .`model`)
        try container.encodeField(`provider`, forKey: .`provider`)
        try container.encodeField(`reasoningEffort`, forKey: .`reasoningEffort`)
        try container.encodeField(`fast`, forKey: .`fast`)
        try container.encodeIfPresent(`closeOnDisconnect`, forKey: .`closeOnDisconnect`)
        try container.encodeIfPresent(`hidden`, forKey: .`hidden`)
        try container.encodeIfPresent(`roomPlumbing`, forKey: .`roomPlumbing`)
        try container.encodeIfPresent(`followProfileConfig`, forKey: .`followProfileConfig`)
    }
}

/// Wire schema: `SessionResumeParams`. Complex referenced objects retain their full JSON structure.
public struct SessionResumeParams: Sendable, Codable, Equatable {
    public var `sessionID`: String
    public var `profile`: JSONField<String>
    public var `cols`: JSONField<Int>
    public var `source`: JSONField<String>
    public var `lazy`: Bool?
    public var `deferHistory`: Bool?
    public var `omitMessages`: Bool?
    public var `eagerBuild`: Bool?
    public var `closeOnDisconnect`: Bool?

    public init(
        `sessionID`: String,
        `profile`: JSONField<String> = .absent,
        `cols`: JSONField<Int> = .absent,
        `source`: JSONField<String> = .absent,
        `lazy`: Bool? = nil,
        `deferHistory`: Bool? = nil,
        `omitMessages`: Bool? = nil,
        `eagerBuild`: Bool? = nil,
        `closeOnDisconnect`: Bool? = nil
    ) {
        self.`sessionID` = `sessionID`
        self.`profile` = `profile`
        self.`cols` = `cols`
        self.`source` = `source`
        self.`lazy` = `lazy`
        self.`deferHistory` = `deferHistory`
        self.`omitMessages` = `omitMessages`
        self.`eagerBuild` = `eagerBuild`
        self.`closeOnDisconnect` = `closeOnDisconnect`
    }

    private enum CodingKeys: String, CodingKey {
        case `sessionID` = "session_id"
        case `profile` = "profile"
        case `cols` = "cols"
        case `source` = "source"
        case `lazy` = "lazy"
        case `deferHistory` = "defer_history"
        case `omitMessages` = "omit_messages"
        case `eagerBuild` = "eager_build"
        case `closeOnDisconnect` = "close_on_disconnect"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `sessionID` = try container.decode(String.self, forKey: .`sessionID`)
        `profile` = try container.decodeField(String.self, forKey: .`profile`)
        `cols` = try container.decodeField(Int.self, forKey: .`cols`)
        `source` = try container.decodeField(String.self, forKey: .`source`)
        `lazy` = try container.decodeOmittable(Bool.self, forKey: .`lazy`)
        `deferHistory` = try container.decodeOmittable(Bool.self, forKey: .`deferHistory`)
        `omitMessages` = try container.decodeOmittable(Bool.self, forKey: .`omitMessages`)
        `eagerBuild` = try container.decodeOmittable(Bool.self, forKey: .`eagerBuild`)
        `closeOnDisconnect` = try container.decodeOmittable(Bool.self, forKey: .`closeOnDisconnect`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`sessionID`, forKey: .`sessionID`)
        try container.encodeField(`profile`, forKey: .`profile`)
        try container.encodeField(`cols`, forKey: .`cols`)
        try container.encodeField(`source`, forKey: .`source`)
        try container.encodeIfPresent(`lazy`, forKey: .`lazy`)
        try container.encodeIfPresent(`deferHistory`, forKey: .`deferHistory`)
        try container.encodeIfPresent(`omitMessages`, forKey: .`omitMessages`)
        try container.encodeIfPresent(`eagerBuild`, forKey: .`eagerBuild`)
        try container.encodeIfPresent(`closeOnDisconnect`, forKey: .`closeOnDisconnect`)
    }
}

/// Wire schema: `SessionActivateParams`. Complex referenced objects retain their full JSON structure.
public struct SessionActivateParams: Sendable, Codable, Equatable {
    public var `sessionID`: String
    public var `profile`: JSONField<String>
    public var `cols`: JSONField<Int>
    public var `omitMessages`: Bool?

    public init(
        `sessionID`: String,
        `profile`: JSONField<String> = .absent,
        `cols`: JSONField<Int> = .absent,
        `omitMessages`: Bool? = nil
    ) {
        self.`sessionID` = `sessionID`
        self.`profile` = `profile`
        self.`cols` = `cols`
        self.`omitMessages` = `omitMessages`
    }

    private enum CodingKeys: String, CodingKey {
        case `sessionID` = "session_id"
        case `profile` = "profile"
        case `cols` = "cols"
        case `omitMessages` = "omit_messages"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `sessionID` = try container.decode(String.self, forKey: .`sessionID`)
        `profile` = try container.decodeField(String.self, forKey: .`profile`)
        `cols` = try container.decodeField(Int.self, forKey: .`cols`)
        `omitMessages` = try container.decodeOmittable(Bool.self, forKey: .`omitMessages`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`sessionID`, forKey: .`sessionID`)
        try container.encodeField(`profile`, forKey: .`profile`)
        try container.encodeField(`cols`, forKey: .`cols`)
        try container.encodeIfPresent(`omitMessages`, forKey: .`omitMessages`)
    }
}

/// Wire schema: `SessionInterruptParams`. Complex referenced objects retain their full JSON structure.
public struct SessionInterruptParams: Sendable, Codable, Equatable {
    public var `sessionID`: String
    public var `profile`: JSONField<String>
    public var `expectedHostedTaskID`: JSONField<String>

    public init(
        `sessionID`: String,
        `profile`: JSONField<String> = .absent,
        `expectedHostedTaskID`: JSONField<String> = .absent
    ) {
        self.`sessionID` = `sessionID`
        self.`profile` = `profile`
        self.`expectedHostedTaskID` = `expectedHostedTaskID`
    }

    private enum CodingKeys: String, CodingKey {
        case `sessionID` = "session_id"
        case `profile` = "profile"
        case `expectedHostedTaskID` = "expected_hosted_task_id"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `sessionID` = try container.decode(String.self, forKey: .`sessionID`)
        `profile` = try container.decodeField(String.self, forKey: .`profile`)
        `expectedHostedTaskID` = try container.decodeField(String.self, forKey: .`expectedHostedTaskID`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`sessionID`, forKey: .`sessionID`)
        try container.encodeField(`profile`, forKey: .`profile`)
        try container.encodeField(`expectedHostedTaskID`, forKey: .`expectedHostedTaskID`)
    }
}

/// Wire schema: `SessionEventsSinceParams`. Complex referenced objects retain their full JSON structure.
public struct SessionEventsSinceParams: Sendable, Codable, Equatable {
    public var `sessionID`: String
    public var `profile`: JSONField<String>
    public var `lastSeen`: JSONField<Int>

    public init(
        `sessionID`: String,
        `profile`: JSONField<String> = .absent,
        `lastSeen`: JSONField<Int> = .absent
    ) {
        self.`sessionID` = `sessionID`
        self.`profile` = `profile`
        self.`lastSeen` = `lastSeen`
    }

    private enum CodingKeys: String, CodingKey {
        case `sessionID` = "session_id"
        case `profile` = "profile"
        case `lastSeen` = "last_seen"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `sessionID` = try container.decode(String.self, forKey: .`sessionID`)
        `profile` = try container.decodeField(String.self, forKey: .`profile`)
        `lastSeen` = try container.decodeField(Int.self, forKey: .`lastSeen`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`sessionID`, forKey: .`sessionID`)
        try container.encodeField(`profile`, forKey: .`profile`)
        try container.encodeField(`lastSeen`, forKey: .`lastSeen`)
    }
}

/// Wire schema: `SessionEventsSinceResult`. Complex referenced objects retain their full JSON structure.
public struct SessionEventsSinceResult: Sendable, Codable, Equatable {
    public var `events`: [JSONValue]
    public var `latestSeq`: Int
    public var `truncated`: Bool
    public var `count`: Int
    public var `epoch`: String
    public var `openRequests`: [JSONValue]

    public init(
        `events`: [JSONValue],
        `latestSeq`: Int,
        `truncated`: Bool,
        `count`: Int,
        `epoch`: String,
        `openRequests`: [JSONValue]
    ) {
        self.`events` = `events`
        self.`latestSeq` = `latestSeq`
        self.`truncated` = `truncated`
        self.`count` = `count`
        self.`epoch` = `epoch`
        self.`openRequests` = `openRequests`
    }

    private enum CodingKeys: String, CodingKey {
        case `events` = "events"
        case `latestSeq` = "latest_seq"
        case `truncated` = "truncated"
        case `count` = "count"
        case `epoch` = "epoch"
        case `openRequests` = "open_requests"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `events` = try container.decode([JSONValue].self, forKey: .`events`)
        `latestSeq` = try container.decode(Int.self, forKey: .`latestSeq`)
        `truncated` = try container.decode(Bool.self, forKey: .`truncated`)
        `count` = try container.decode(Int.self, forKey: .`count`)
        `epoch` = try container.decode(String.self, forKey: .`epoch`)
        `openRequests` = try container.decode([JSONValue].self, forKey: .`openRequests`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`events`, forKey: .`events`)
        try container.encode(`latestSeq`, forKey: .`latestSeq`)
        try container.encode(`truncated`, forKey: .`truncated`)
        try container.encode(`count`, forKey: .`count`)
        try container.encode(`epoch`, forKey: .`epoch`)
        try container.encode(`openRequests`, forKey: .`openRequests`)
    }
}

/// Wire schema: `PromptSubmitParams`. Complex referenced objects retain their full JSON structure.
public struct PromptSubmitParams: Sendable, Codable, Equatable {
    public var `sessionID`: String
    public var `profile`: JSONField<String>
    public var `text`: JSONValue?
    public var `displayKind`: JSONField<String>
    public var `interrupted`: JSONField<Bool>
    public var `queued`: JSONField<Bool>
    public var `surface`: JSONField<String>
    public var `voiceContext`: JSONField<String>
    public var `truncateBeforeUserOrdinal`: JSONField<Int>
    public var `truncateBeforeRowID`: JSONField<Int>
    public var `truncateBeforeMessageID`: JSONField<String>
    public var `confirmTruncate`: JSONField<Bool>
    public var `confirmEmptyTruncate`: JSONField<Bool>
    public var `rebindSurvivorRowIDs`: JSONField<[Int]>

    public init(
        `sessionID`: String,
        `profile`: JSONField<String> = .absent,
        `text`: JSONValue? = nil,
        `displayKind`: JSONField<String> = .absent,
        `interrupted`: JSONField<Bool> = .absent,
        `queued`: JSONField<Bool> = .absent,
        `surface`: JSONField<String> = .absent,
        `voiceContext`: JSONField<String> = .absent,
        `truncateBeforeUserOrdinal`: JSONField<Int> = .absent,
        `truncateBeforeRowID`: JSONField<Int> = .absent,
        `truncateBeforeMessageID`: JSONField<String> = .absent,
        `confirmTruncate`: JSONField<Bool> = .absent,
        `confirmEmptyTruncate`: JSONField<Bool> = .absent,
        `rebindSurvivorRowIDs`: JSONField<[Int]> = .absent
    ) {
        self.`sessionID` = `sessionID`
        self.`profile` = `profile`
        self.`text` = `text`
        self.`displayKind` = `displayKind`
        self.`interrupted` = `interrupted`
        self.`queued` = `queued`
        self.`surface` = `surface`
        self.`voiceContext` = `voiceContext`
        self.`truncateBeforeUserOrdinal` = `truncateBeforeUserOrdinal`
        self.`truncateBeforeRowID` = `truncateBeforeRowID`
        self.`truncateBeforeMessageID` = `truncateBeforeMessageID`
        self.`confirmTruncate` = `confirmTruncate`
        self.`confirmEmptyTruncate` = `confirmEmptyTruncate`
        self.`rebindSurvivorRowIDs` = `rebindSurvivorRowIDs`
    }

    private enum CodingKeys: String, CodingKey {
        case `sessionID` = "session_id"
        case `profile` = "profile"
        case `text` = "text"
        case `displayKind` = "display_kind"
        case `interrupted` = "interrupted"
        case `queued` = "queued"
        case `surface` = "surface"
        case `voiceContext` = "voice_context"
        case `truncateBeforeUserOrdinal` = "truncate_before_user_ordinal"
        case `truncateBeforeRowID` = "truncate_before_row_id"
        case `truncateBeforeMessageID` = "truncate_before_message_id"
        case `confirmTruncate` = "confirm_truncate"
        case `confirmEmptyTruncate` = "confirm_empty_truncate"
        case `rebindSurvivorRowIDs` = "rebind_survivor_row_ids"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `sessionID` = try container.decode(String.self, forKey: .`sessionID`)
        `profile` = try container.decodeField(String.self, forKey: .`profile`)
        `text` = try container.decodeOmittable(JSONValue.self, forKey: .`text`)
        `displayKind` = try container.decodeField(String.self, forKey: .`displayKind`)
        `interrupted` = try container.decodeField(Bool.self, forKey: .`interrupted`)
        `queued` = try container.decodeField(Bool.self, forKey: .`queued`)
        `surface` = try container.decodeField(String.self, forKey: .`surface`)
        `voiceContext` = try container.decodeField(String.self, forKey: .`voiceContext`)
        `truncateBeforeUserOrdinal` = try container.decodeField(Int.self, forKey: .`truncateBeforeUserOrdinal`)
        `truncateBeforeRowID` = try container.decodeField(Int.self, forKey: .`truncateBeforeRowID`)
        `truncateBeforeMessageID` = try container.decodeField(String.self, forKey: .`truncateBeforeMessageID`)
        `confirmTruncate` = try container.decodeField(Bool.self, forKey: .`confirmTruncate`)
        `confirmEmptyTruncate` = try container.decodeField(Bool.self, forKey: .`confirmEmptyTruncate`)
        `rebindSurvivorRowIDs` = try container.decodeField([Int].self, forKey: .`rebindSurvivorRowIDs`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`sessionID`, forKey: .`sessionID`)
        try container.encodeField(`profile`, forKey: .`profile`)
        try container.encodeIfPresent(`text`, forKey: .`text`)
        try container.encodeField(`displayKind`, forKey: .`displayKind`)
        try container.encodeField(`interrupted`, forKey: .`interrupted`)
        try container.encodeField(`queued`, forKey: .`queued`)
        try container.encodeField(`surface`, forKey: .`surface`)
        try container.encodeField(`voiceContext`, forKey: .`voiceContext`)
        try container.encodeField(`truncateBeforeUserOrdinal`, forKey: .`truncateBeforeUserOrdinal`)
        try container.encodeField(`truncateBeforeRowID`, forKey: .`truncateBeforeRowID`)
        try container.encodeField(`truncateBeforeMessageID`, forKey: .`truncateBeforeMessageID`)
        try container.encodeField(`confirmTruncate`, forKey: .`confirmTruncate`)
        try container.encodeField(`confirmEmptyTruncate`, forKey: .`confirmEmptyTruncate`)
        try container.encodeField(`rebindSurvivorRowIDs`, forKey: .`rebindSurvivorRowIDs`)
    }
}

/// Wire schema: `PromptSubmitResult`. Complex referenced objects retain their full JSON structure.
public struct PromptSubmitResult: Sendable, Codable, Equatable {
    public var `status`: JSONField<String>
    public var `voiceStopped`: JSONField<Bool>
    public var `survivorUserRowIDs`: JSONField<[Int?]>
    public var `survivorRowIDMap`: JSONField<[String: Int?]>
    public var `turnIsolation`: JSONField<Bool>

    public init(
        `status`: JSONField<String> = .absent,
        `voiceStopped`: JSONField<Bool> = .absent,
        `survivorUserRowIDs`: JSONField<[Int?]> = .absent,
        `survivorRowIDMap`: JSONField<[String: Int?]> = .absent,
        `turnIsolation`: JSONField<Bool> = .absent
    ) {
        self.`status` = `status`
        self.`voiceStopped` = `voiceStopped`
        self.`survivorUserRowIDs` = `survivorUserRowIDs`
        self.`survivorRowIDMap` = `survivorRowIDMap`
        self.`turnIsolation` = `turnIsolation`
    }

    private enum CodingKeys: String, CodingKey {
        case `status` = "status"
        case `voiceStopped` = "voice_stopped"
        case `survivorUserRowIDs` = "survivor_user_row_ids"
        case `survivorRowIDMap` = "survivor_row_id_map"
        case `turnIsolation` = "turn_isolation"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `status` = try container.decodeField(String.self, forKey: .`status`)
        `voiceStopped` = try container.decodeField(Bool.self, forKey: .`voiceStopped`)
        `survivorUserRowIDs` = try container.decodeField([Int?].self, forKey: .`survivorUserRowIDs`)
        `survivorRowIDMap` = try container.decodeField([String: Int?].self, forKey: .`survivorRowIDMap`)
        `turnIsolation` = try container.decodeField(Bool.self, forKey: .`turnIsolation`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeField(`status`, forKey: .`status`)
        try container.encodeField(`voiceStopped`, forKey: .`voiceStopped`)
        try container.encodeField(`survivorUserRowIDs`, forKey: .`survivorUserRowIDs`)
        try container.encodeField(`survivorRowIDMap`, forKey: .`survivorRowIDMap`)
        try container.encodeField(`turnIsolation`, forKey: .`turnIsolation`)
    }
}

/// Wire schema: `GatewayReadyPayload`. Complex referenced objects retain their full JSON structure.
public struct GatewayReadyPayload: Sendable, Codable, Equatable {
    public var `skin`: JSONValue
    public var `changeEvents`: Bool
    public var `replayEpoch`: String
    public var `heartbeat`: JSONField<Bool>

    public init(
        `skin`: JSONValue,
        `changeEvents`: Bool,
        `replayEpoch`: String,
        `heartbeat`: JSONField<Bool> = .absent
    ) {
        self.`skin` = `skin`
        self.`changeEvents` = `changeEvents`
        self.`replayEpoch` = `replayEpoch`
        self.`heartbeat` = `heartbeat`
    }

    private enum CodingKeys: String, CodingKey {
        case `skin` = "skin"
        case `changeEvents` = "change_events"
        case `replayEpoch` = "replay_epoch"
        case `heartbeat` = "heartbeat"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `skin` = try container.decode(JSONValue.self, forKey: .`skin`)
        `changeEvents` = try container.decode(Bool.self, forKey: .`changeEvents`)
        `replayEpoch` = try container.decode(String.self, forKey: .`replayEpoch`)
        `heartbeat` = try container.decodeField(Bool.self, forKey: .`heartbeat`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`skin`, forKey: .`skin`)
        try container.encode(`changeEvents`, forKey: .`changeEvents`)
        try container.encode(`replayEpoch`, forKey: .`replayEpoch`)
        try container.encodeField(`heartbeat`, forKey: .`heartbeat`)
    }
}

/// Wire schema: `StreamDeltaPayload`. Complex referenced objects retain their full JSON structure.
public struct StreamDeltaPayload: Sendable, Codable, Equatable {
    public var `text`: String
    public var `rendered`: JSONField<String>
    public var `verbose`: JSONField<Bool>

    public init(
        `text`: String,
        `rendered`: JSONField<String> = .absent,
        `verbose`: JSONField<Bool> = .absent
    ) {
        self.`text` = `text`
        self.`rendered` = `rendered`
        self.`verbose` = `verbose`
    }

    private enum CodingKeys: String, CodingKey {
        case `text` = "text"
        case `rendered` = "rendered"
        case `verbose` = "verbose"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `text` = try container.decode(String.self, forKey: .`text`)
        `rendered` = try container.decodeField(String.self, forKey: .`rendered`)
        `verbose` = try container.decodeField(Bool.self, forKey: .`verbose`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`text`, forKey: .`text`)
        try container.encodeField(`rendered`, forKey: .`rendered`)
        try container.encodeField(`verbose`, forKey: .`verbose`)
    }
}

/// Wire schema: `MessageCompletePayload`. Complex referenced objects retain their full JSON structure.
public struct MessageCompletePayload: Sendable, Codable, Equatable {
    public var `text`: JSONValue?
    public var `usage`: JSONField<JSONValue>
    public var `status`: JSONField<String>
    public var `reasoning`: JSONField<String>
    public var `warning`: JSONField<String>
    public var `responsePreviewed`: JSONField<Bool>
    public var `billing`: JSONField<JSONValue>
    public var `failureReason`: JSONField<String>
    public var `rendered`: JSONField<String>
    public var `error`: JSONField<String>
    public var `recoverable`: JSONField<Bool>
    public var `errorSurface`: JSONField<JSONValue>
    public var `partial`: JSONField<Bool>

    public init(
        `text`: JSONValue? = nil,
        `usage`: JSONField<JSONValue> = .absent,
        `status`: JSONField<String> = .absent,
        `reasoning`: JSONField<String> = .absent,
        `warning`: JSONField<String> = .absent,
        `responsePreviewed`: JSONField<Bool> = .absent,
        `billing`: JSONField<JSONValue> = .absent,
        `failureReason`: JSONField<String> = .absent,
        `rendered`: JSONField<String> = .absent,
        `error`: JSONField<String> = .absent,
        `recoverable`: JSONField<Bool> = .absent,
        `errorSurface`: JSONField<JSONValue> = .absent,
        `partial`: JSONField<Bool> = .absent
    ) {
        self.`text` = `text`
        self.`usage` = `usage`
        self.`status` = `status`
        self.`reasoning` = `reasoning`
        self.`warning` = `warning`
        self.`responsePreviewed` = `responsePreviewed`
        self.`billing` = `billing`
        self.`failureReason` = `failureReason`
        self.`rendered` = `rendered`
        self.`error` = `error`
        self.`recoverable` = `recoverable`
        self.`errorSurface` = `errorSurface`
        self.`partial` = `partial`
    }

    private enum CodingKeys: String, CodingKey {
        case `text` = "text"
        case `usage` = "usage"
        case `status` = "status"
        case `reasoning` = "reasoning"
        case `warning` = "warning"
        case `responsePreviewed` = "response_previewed"
        case `billing` = "billing"
        case `failureReason` = "failure_reason"
        case `rendered` = "rendered"
        case `error` = "error"
        case `recoverable` = "recoverable"
        case `errorSurface` = "error_surface"
        case `partial` = "partial"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `text` = try container.decodeOmittable(JSONValue.self, forKey: .`text`)
        `usage` = try container.decodeField(JSONValue.self, forKey: .`usage`)
        `status` = try container.decodeField(String.self, forKey: .`status`)
        `reasoning` = try container.decodeField(String.self, forKey: .`reasoning`)
        `warning` = try container.decodeField(String.self, forKey: .`warning`)
        `responsePreviewed` = try container.decodeField(Bool.self, forKey: .`responsePreviewed`)
        `billing` = try container.decodeField(JSONValue.self, forKey: .`billing`)
        `failureReason` = try container.decodeField(String.self, forKey: .`failureReason`)
        `rendered` = try container.decodeField(String.self, forKey: .`rendered`)
        `error` = try container.decodeField(String.self, forKey: .`error`)
        `recoverable` = try container.decodeField(Bool.self, forKey: .`recoverable`)
        `errorSurface` = try container.decodeField(JSONValue.self, forKey: .`errorSurface`)
        `partial` = try container.decodeField(Bool.self, forKey: .`partial`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(`text`, forKey: .`text`)
        try container.encodeField(`usage`, forKey: .`usage`)
        try container.encodeField(`status`, forKey: .`status`)
        try container.encodeField(`reasoning`, forKey: .`reasoning`)
        try container.encodeField(`warning`, forKey: .`warning`)
        try container.encodeField(`responsePreviewed`, forKey: .`responsePreviewed`)
        try container.encodeField(`billing`, forKey: .`billing`)
        try container.encodeField(`failureReason`, forKey: .`failureReason`)
        try container.encodeField(`rendered`, forKey: .`rendered`)
        try container.encodeField(`error`, forKey: .`error`)
        try container.encodeField(`recoverable`, forKey: .`recoverable`)
        try container.encodeField(`errorSurface`, forKey: .`errorSurface`)
        try container.encodeField(`partial`, forKey: .`partial`)
    }
}

/// Wire schema: `ApprovalResult`. Complex referenced objects retain their full JSON structure.
public struct ApprovalResult: Sendable, Codable, Equatable {
    public var `choice`: String
    public var `all`: JSONField<Bool>

    public init(
        `choice`: String,
        `all`: JSONField<Bool> = .absent
    ) {
        self.`choice` = `choice`
        self.`all` = `all`
    }

    private enum CodingKeys: String, CodingKey {
        case `choice` = "choice"
        case `all` = "all"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `choice` = try container.decode(String.self, forKey: .`choice`)
        `all` = try container.decodeField(Bool.self, forKey: .`all`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`choice`, forKey: .`choice`)
        try container.encodeField(`all`, forKey: .`all`)
    }
}

/// Wire schema: `ClarifyResult`. Complex referenced objects retain their full JSON structure.
public struct ClarifyResult: Sendable, Codable, Equatable {
    public var `answer`: JSONField<String>
    public var `answers`: JSONField<[String: String]>

    public init(
        `answer`: JSONField<String> = .absent,
        `answers`: JSONField<[String: String]> = .absent
    ) {
        self.`answer` = `answer`
        self.`answers` = `answers`
    }

    private enum CodingKeys: String, CodingKey {
        case `answer` = "answer"
        case `answers` = "answers"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        `answer` = try container.decodeField(String.self, forKey: .`answer`)
        `answers` = try container.decodeField([String: String].self, forKey: .`answers`)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeField(`answer`, forKey: .`answer`)
        try container.encodeField(`answers`, forKey: .`answers`)
    }
}
